### PR TITLE
Test fixes to use correct ResolveTypeFn and add types to Schema

### PR DESCRIPTION
**Pull request by object88**
Fixes for tests, so they cooperate with the current version of [graphql](https://github.com/graphql-go/graphql).  See issue #26.

### CODE REVIEW

**Comment by object88** [comment]
Ah, sorry, I hadn't realized that the code in `examples` is tested separately.  Will address this and try again.

**Comment by object88** [comment]
Should be fixed now; seems to be passing the checks.

**Comment by dsoprea** [comment]
Bump. Can we get this merged?

**Comment by muhqu** [comment]
@sogko or @chris-ramon any chance you get this merged?

**Comment by johanoskarsson** [comment]
Bump again. I ran into this as well. Fix LGTM

**Comment by SCKelemen** [comment]
Bump

**Comment by danyim** [comment]
Can we get this merged?

**Comment by whosthatknocking** [comment]
Any blockers to get this out?

**Comment by chris-ramon** [comment]
thanks a lot guys! :ship:

**Pull request merged**
